version: '2'
services:
  openvpn-ca:
    image: silentdigit/openvpn:latest
    container_name: openvpn
    environment:
      - EASYRSA_KEY_SIZE=4096
    restart: unless-stopped
    volumes:
     - ./openvpn-data-ca:/etc/openvpn
