version: '2'

# Base docker-compose file modified for VPN server

services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: silentdigit/openvpn:latest
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./openvpn-data-server:/etc/openvpn
